#' Load the generated rpact function catalog
#'
#' The catalog is generated by `data-raw/build_catalog.R` from the installed
#' rpact namespace and drives every function form in the app. It is the
#' single source of truth for which functions the dashboard covers.
#'
#' @return A list with `meta` (generation metadata) and `functions`
#'   (one entry per catalogued rpact function).
#' @export
load_catalog <- function() {
  path <- system.file("catalog", "functions.json", package = "rpactdash")
  if (path == "") {
    # During development (package loaded via source, not installed)
    path <- file.path("inst", "catalog", "functions.json")
  }
  if (!file.exists(path)) {
    stop("Function catalog not found. Run data-raw/build_catalog.R first.")
  }
  jsonlite::read_json(path)
}

#' Subset catalog entries by module family
#' @param catalog A catalog as returned by [load_catalog()].
#' @param family One of "design", "samplesize_power", "simulation",
#'   "analysis", "utility".
#' @keywords internal
catalog_family <- function(catalog, family) {
  Filter(function(f) identical(f$family, family), catalog$functions)
}
